Repository OS2mo/os2mo, pull requests merged in 2018-06, with the labels that each got.

#115 #21716 configurable paging
  Jenkinsfile
  mora/lora.py
  mora/service/details.py
  mora/service/employee.py
  mora/service/facet.py
  mora/service/orgunit.py
  mora/settings.py
  tests/test_integration_importing.py
Labels: enhancement, middle-end

#117 include validity when returning organisational units
  mora/service/orgunit.py
  tests/test_integration_address.py
  tests/test_integration_association.py
  tests/test_integration_importing.py
  tests/test_integration_manager.py
  tests/test_integration_org_unit.py
  tests/test_integration_service.py
Labels: api-change, middle-end

#119 Feature/21273 test fixes
  Jenkinsfile
  mora/lora.py
  tests/fixtures/importing/BALLERUP_EXTRA__bruger__0.csv
  tests/fixtures/importing/BALLERUP__bruger__0.csv
  tests/test_integration_importing.py
  tests/test_integration_service.py
Labels: middle-end
